### ISSUE TITLE
Spamming my taskbar

### ISSUE THREAD

**Issue by mdennis281** [tnewton1/ZeroTierOneFixer#2]
Am I the only one with this problem?

![image](https://user-images.githubusercontent.com/16827865/80711754-7a5fc880-8ab6-11ea-8628-981ff9f0ad2e.png)

it makes sense why it's happening- im just wondering why this line:
`Start-Process $ZeroTierOneExe`

isnt something like this:
```powershell
$ZeroTierAlive = Get-Process -Name "ZeroTier One" -ErrorAction SilentlyContinue

if($ZeroTierAlive -eq $null){
    Start-Process $ZeroTierOneExe
}
```

**Comment by tnewton1** [comment]
This is a valid issue. The script needs to be cleaned up and re-worked. I'll look into it, but I haven't used ZeroTier in a couple of years now. If you (or anyone who actively uses ZeroTier) can contribute, I'll merge in any contributions. Otherwise, I'll look into it but I don't have an ETA.

**Comment by mdennis281** [comment]
I made the aforementioned changes. It definitely fixes the taskbar issue-

I'll let it sit like this a month and report back if any unexpected issues arise. thanks for the quick response.

**Comment by tnewton1** [comment]
@mdennis281 Thanks for helping to contribute! Do let me know. I'll branch this off and do some more tweaking and testing.

**Comment by tnewton1** [comment]
@mdennis281 Thanks for helping out! 👍
